name: mobilecity-searching
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  db-api:
    build:
      dockerfile: Dockerfile
      context: ./db-api
    volumes:
      - ./db-api:/app:ro
    expose:
      - 8000
    environment:
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      db:
        condition: service_healthy

  crawler:
    build:
      dockerfile: Dockerfile
      context: ./crawler
    expose:
      - 8000
    volumes:
      - ./crawler:/app:ro
      - ./landing_zone:/landing_zone
    environment:
      - CRAWL_HOUR=${CRAWL_HOUR}
      - CRAWL_MINUTE=${CRAWL_MINUTE}
      - INGESTION_SERVICE_URL=http://ingestion:8000
      - TZ=Asia/Ho_Chi_Minh

  ingestion:
    build:
      dockerfile: Dockerfile
      context: ./ingestion
    expose:
      - 8000
    volumes:
      - ./ingestion:/app:ro
      - ./landing_zone:/landing_zone
    environment:
      - LANDING_ZONE_MAX_FILE_AGE=${LANDING_ZONE_MAX_FILE_AGE}
      - DB_API_URL=http://db-api:8000
      - TZ=Asia/Ho_Chi_Minh

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - crawler
      - ingestion
      - db-api
      - frontend

  # production
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - db-api
    environment:
      - VITE_API_URL=http://localhost:8000

  # development
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   container_name: frontend
  #   volumes:
  #     # - ./frontend/src:/app/src
  #     - ./frontend:/app
  #     - /app/node_modules
  #   expose:
  #     - 3000
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db-api
  #   environment:
  #     - VITE_API_URL=http://localhost:8000

volumes:
  postgres_data:
